/**
 * Particle Flow Field Visualization
 * Particles flow through force fields generated by Perlin noise and body positions
 */
class ParticleField extends BaseVisualization {
    constructor(canvas, ctx) {
        super(canvas, ctx);

        this.particles = [];
        this.flowField = [];
        this.cols = 0;
        this.rows = 0;
        this.resolution = 20; // Grid resolution for flow field
        this.noiseScale = 0.01;
        this.noiseZ = 0; // For animating the noise field

        // Track previous joint positions for velocity calculation
        this.previousJoints = new Map();

        // Default parameters
        this.params = {
            particleCount: 5000,
            forceStrength: 1.0,
            flowSpeed: 0.5,
            particleSize: 2,
            trailLength: 0.95,
            colorMode: 'heatmap'
        };
    }

    init() {
        // Calculate flow field dimensions
        this.cols = Math.floor(this.width / this.resolution);
        this.rows = Math.floor(this.height / this.resolution);

        // Initialize flow field
        this.flowField = new Array(this.cols * this.rows);
        this.updateFlowField();

        // Initialize particles
        this.particles = [];
        for (let i = 0; i < this.params.particleCount; i++) {
            this.particles.push(new Particle(this.width, this.height));
        }
    }

    update(deltaTime) {
        // Animate the flow field
        this.noiseZ += 0.001 * this.params.flowSpeed;
        this.updateFlowField();

        // Update all particles
        for (let particle of this.particles) {
            this.applyFlowField(particle);
            this.applyBodyForces(particle);
            particle.update(deltaTime);
            particle.wrap(this.width, this.height);
        }
    }

    updateFlowField() {
        let index = 0;
        for (let y = 0; y < this.rows; y++) {
            for (let x = 0; x < this.cols; x++) {
                // Use Perlin noise to generate flow field angles
                let angle = this.noise3D(
                    x * this.noiseScale,
                    y * this.noiseScale,
                    this.noiseZ
                ) * Math.PI * 2;

                this.flowField[index] = {
                    x: Math.cos(angle),
                    y: Math.sin(angle)
                };
                index++;
            }
        }
    }

    applyFlowField(particle) {
        // Get the flow field vector at particle position
        const x = Math.floor(particle.pos.x / this.resolution);
        const y = Math.floor(particle.pos.y / this.resolution);
        const index = x + y * this.cols;

        if (this.flowField[index]) {
            const force = this.flowField[index];
            particle.applyForce(
                force.x * this.params.forceStrength * 0.5,
                force.y * this.params.forceStrength * 0.5
            );
        }
    }

    applyBodyForces(particle) {
        // Apply forces from tracked bodies
        for (let body of this.bodyData) {
            if (!body.joints) continue;

            // Create attraction/repulsion from key joints
            const keyJoints = ['handLeft', 'handRight', 'head', 'pelvis'];

            for (let jointName of keyJoints) {
                const joint = body.joints[jointName];
                if (!joint) continue;

                // Convert joint position to screen coordinates
                const jointX = joint.x * this.width;
                const jointY = joint.y * this.height;

                const dx = jointX - particle.pos.x;
                const dy = jointY - particle.pos.y;
                const distSq = dx * dx + dy * dy;
                const dist = Math.sqrt(distSq);

                // Calculate joint velocity for explosive bursts
                const jointKey = `${body.id}_${jointName}`;
                const prevJoint = this.previousJoints.get(jointKey);
                let jointVelocity = 0;

                if (prevJoint) {
                    const vx = (joint.x - prevJoint.x) * this.width;
                    const vy = (joint.y - prevJoint.y) * this.height;
                    jointVelocity = Math.sqrt(vx * vx + vy * vy);
                }

                // Store current position for next frame
                this.previousJoints.set(jointKey, { x: joint.x, y: joint.y });

                const influenceRadius = 200 + (jointVelocity * 20); // Radius grows with speed

                if (dist < influenceRadius && dist > 0) {
                    // Normalize distance vector
                    const ndx = dx / dist;
                    const ndy = dy / dist;

                    // Calculate falloff (closer = stronger)
                    const falloff = 1 - (dist / influenceRadius);

                    // Base strength from parameters
                    const baseStrength = this.params.forceStrength;

                    // VORTEX FORCE: Tangential component (perpendicular to radial)
                    // Creates spiraling motion around the joint
                    const vortexStrength = baseStrength * falloff * 3;
                    const tangentX = -ndy; // Perpendicular to radial direction
                    const tangentY = ndx;

                    particle.applyForce(
                        tangentX * vortexStrength,
                        tangentY * vortexStrength
                    );

                    // REPULSION FORCE: Push particles away (weaker than vortex)
                    const repulsionStrength = baseStrength * falloff * 1.5;
                    particle.applyForce(
                        -ndx * repulsionStrength,
                        -ndy * repulsionStrength
                    );

                    // EXPLOSIVE BURST: When joint moves fast, create strong outward force
                    if (jointVelocity > 5) {
                        const burstStrength = jointVelocity * falloff * 0.8;
                        particle.applyForce(
                            -ndx * burstStrength,
                            -ndy * burstStrength
                        );

                        // Add some random scatter to explosion
                        const randomAngle = Math.random() * Math.PI * 2;
                        const randomStr = burstStrength * 0.3;
                        particle.applyForce(
                            Math.cos(randomAngle) * randomStr,
                            Math.sin(randomAngle) * randomStr
                        );
                    }
                }
            }
        }
    }

    render() {
        // Apply trail effect by drawing semi-transparent rectangle
        this.ctx.fillStyle = `rgba(0, 0, 0, ${1 - this.params.trailLength})`;
        this.ctx.fillRect(0, 0, this.width, this.height);

        // Draw particles
        for (let particle of this.particles) {
            const color = this.getParticleColor(particle);
            this.ctx.fillStyle = color;
            this.ctx.beginPath();
            this.ctx.arc(
                particle.pos.x,
                particle.pos.y,
                this.params.particleSize,
                0,
                Math.PI * 2
            );
            this.ctx.fill();
        }
    }

    getParticleColor(particle) {
        switch (this.params.colorMode) {
            case 'velocity': {
                const speed = Math.sqrt(
                    particle.vel.x * particle.vel.x +
                    particle.vel.y * particle.vel.y
                );
                const hue = (speed * 10) % 360;
                return `hsla(${hue}, 70%, 60%, 0.8)`;
            }

            case 'heatmap': {
                // Heat map: slow = cool blue, medium = green/yellow, fast = hot red
                const speed = Math.sqrt(
                    particle.vel.x * particle.vel.x +
                    particle.vel.y * particle.vel.y
                );

                // Normalize speed (0 to ~8 for typical particle speeds)
                const normalizedSpeed = Math.min(speed / 8, 1);

                let r, g, b;
                if (normalizedSpeed < 0.25) {
                    // Very slow: Deep blue to cyan
                    const t = normalizedSpeed / 0.25;
                    r = 0;
                    g = Math.floor(t * 100);
                    b = Math.floor(150 + t * 105);
                } else if (normalizedSpeed < 0.5) {
                    // Slow to medium: Cyan to green
                    const t = (normalizedSpeed - 0.25) / 0.25;
                    r = 0;
                    g = Math.floor(100 + t * 155);
                    b = Math.floor(255 - t * 155);
                } else if (normalizedSpeed < 0.75) {
                    // Medium to fast: Green to yellow/orange
                    const t = (normalizedSpeed - 0.5) / 0.25;
                    r = Math.floor(t * 255);
                    g = 255;
                    b = Math.floor(100 - t * 100);
                } else {
                    // Fast: Orange to red
                    const t = (normalizedSpeed - 0.75) / 0.25;
                    r = 255;
                    g = Math.floor(255 - t * 155);
                    b = 0;
                }

                return `rgba(${r}, ${g}, ${b}, 0.9)`;
            }

            case 'position': {
                const hue = (particle.pos.x / this.width * 360) % 360;
                return `hsla(${hue}, 70%, 60%, 0.8)`;
            }

            case 'white':
                return 'rgba(255, 255, 255, 0.8)';

            case 'rainbow': {
                const hue = (Date.now() * 0.05 + particle.id * 0.5) % 360;
                return `hsla(${hue}, 70%, 60%, 0.8)`;
            }

            default:
                return 'rgba(255, 255, 255, 0.8)';
        }
    }

    updateParams(params) {
        super.updateParams(params);

        // Handle particle count changes
        if (params.particleCount !== undefined) {
            const diff = params.particleCount - this.particles.length;

            if (diff > 0) {
                // Add particles
                for (let i = 0; i < diff; i++) {
                    this.particles.push(new Particle(this.width, this.height));
                }
            } else if (diff < 0) {
                // Remove particles
                this.particles = this.particles.slice(0, params.particleCount);
            }
        }
    }

    resize(width, height) {
        super.resize(width, height);
        this.cols = Math.floor(this.width / this.resolution);
        this.rows = Math.floor(this.height / this.resolution);
        this.flowField = new Array(this.cols * this.rows);
    }

    /**
     * Simple 3D Perlin-like noise function
     * Using a simplified noise for performance
     */
    noise3D(x, y, z) {
        // Simplified noise using sine waves
        // For better noise, consider using a library like simplex-noise
        return (
            Math.sin(x * 1.2 + z) * 0.5 +
            Math.sin(y * 1.5 - z) * 0.5 +
            Math.sin((x + y) * 0.8 + z * 2) * 0.3
        );
    }
}

/**
 * Individual particle class
 */
class Particle {
    static nextId = 0;

    constructor(maxX, maxY) {
        this.id = Particle.nextId++;
        this.pos = {
            x: Math.random() * maxX,
            y: Math.random() * maxY
        };
        this.vel = { x: 0, y: 0 };
        this.acc = { x: 0, y: 0 };
        this.maxSpeed = 8; // Increased for more dramatic color changes
        this.maxForce = 0.5;
    }

    applyForce(x, y) {
        this.acc.x += x;
        this.acc.y += y;
    }

    update(deltaTime) {
        // Update velocity
        this.vel.x += this.acc.x;
        this.vel.y += this.acc.y;

        // Limit speed
        const speed = Math.sqrt(this.vel.x * this.vel.x + this.vel.y * this.vel.y);
        if (speed > this.maxSpeed) {
            this.vel.x = (this.vel.x / speed) * this.maxSpeed;
            this.vel.y = (this.vel.y / speed) * this.maxSpeed;
        }

        // Update position
        this.pos.x += this.vel.x;
        this.pos.y += this.vel.y;

        // Reset acceleration
        this.acc.x = 0;
        this.acc.y = 0;

        // Apply friction
        this.vel.x *= 0.99;
        this.vel.y *= 0.99;
    }

    wrap(maxX, maxY) {
        // Wrap around screen edges
        if (this.pos.x < 0) this.pos.x = maxX;
        if (this.pos.x > maxX) this.pos.x = 0;
        if (this.pos.y < 0) this.pos.y = maxY;
        if (this.pos.y > maxY) this.pos.y = 0;
    }
}
